### ISSUE TITLE
load plugins first from .i18nrc

### ISSUE THREAD

**Issue by jenseng** [jenseng/i18nliner-js#14]
since plugins might define new i18nliner settings, we should initialize all plugins specified in `.i18nrc` _before_ any other settings in that file ... otherwise the plugin might overwrite those user overrides

**Comment by designfrontier** [comment]
but then... how do they get the settings? Might be better to allow setting of per plugin configs.

**Comment by jenseng** [comment]
really it could go either way, so long as the contract is clear (which it hasn't been)...

if plugins load first, they should expect that they won't know all the settings at require time (react-i18nliner was getting tripped up by this)

if plugins load last, they should only set their own defaults on the config object if they are not already overridden by the user

in any event, i'm fine with the latter. per plugin configs could be nice, but even that could be tripped up by the second problem
