### ISSUE TITLE
Parameterized i18nliner export

### ISSUE THREAD

**Issue by Celestz** [jenseng/i18nliner-js#17]
Hello, is there a way to tell i18nliner export to only search specific folders and specify an output file?

i.e. i18nliner --search /path/to/folder --output /path/to/json

Thanks :)

**Comment by jenseng** [comment]
Yes...

`i18nliner export --only models --outputFile foo.json`

`--only` accepts directories or globs. This option carries over from the check command

Looks like `--outputFile` isn't documented, I'll add it to the README (we can leave this ticket open)

One other thing, if you only ever want to look in a certain directory, you can add something to `.i18nrc` to speed up i18nliner:

```json
{
  "directories": ["jsapp"]
}
```

**Comment by jenseng** [comment]
One note about using `--only` in conjunction with `directories` (in `.i18nrc`) ... `--only` is relative to the `directories` (the default `directories` is effectively `["."]`)
